// OpsGaurd management-plane gRPC contract between the server (OpsGaurdWeb)
// and the Worker agent.
//
// This service replaces the previous HTTP management API (workerproxy ↔
// orchestrator/api.go). The node-level local API (nodeagent, used for
// manager↔node proxying) stays on HTTP and is out of scope.
//
// Direction & network policy: the server initiates every call (the network
// only allows server → worker). SubscribeEvents / SubscribeAudit are
// bidirectional streams opened by the server: the same server-initiated
// connection carries Worker→server event delivery, so the one-way policy
// still holds while push semantics are achieved.
//
// go_package is intentionally omitted here; it is supplied per-module via
// protoc -go_opt=Mopsguard.proto=... so the same .proto compiles into two
// independent module paths (Worker server side, OpsGaurdWeb client side).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.1
// source: opsguard.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ManagementService_Ping_FullMethodName             = "/opsguard.v1.ManagementService/Ping"
	ManagementService_Self_FullMethodName             = "/opsguard.v1.ManagementService/Self"
	ManagementService_ListServices_FullMethodName     = "/opsguard.v1.ManagementService/ListServices"
	ManagementService_GetService_FullMethodName       = "/opsguard.v1.ManagementService/GetService"
	ManagementService_Deploy_FullMethodName           = "/opsguard.v1.ManagementService/Deploy"
	ManagementService_Update_FullMethodName           = "/opsguard.v1.ManagementService/Update"
	ManagementService_Scale_FullMethodName            = "/opsguard.v1.ManagementService/Scale"
	ManagementService_Restart_FullMethodName          = "/opsguard.v1.ManagementService/Restart"
	ManagementService_Remove_FullMethodName           = "/opsguard.v1.ManagementService/Remove"
	ManagementService_GetOperation_FullMethodName     = "/opsguard.v1.ManagementService/GetOperation"
	ManagementService_ListNodes_FullMethodName        = "/opsguard.v1.ManagementService/ListNodes"
	ManagementService_NodeStats_FullMethodName        = "/opsguard.v1.ManagementService/NodeStats"
	ManagementService_NodeProcesses_FullMethodName    = "/opsguard.v1.ManagementService/NodeProcesses"
	ManagementService_NodeContainers_FullMethodName   = "/opsguard.v1.ManagementService/NodeContainers"
	ManagementService_RestartContainer_FullMethodName = "/opsguard.v1.ManagementService/RestartContainer"
	ManagementService_CheckPort_FullMethodName        = "/opsguard.v1.ManagementService/CheckPort"
	ManagementService_CheckHTTP_FullMethodName        = "/opsguard.v1.ManagementService/CheckHTTP"
	ManagementService_CheckFlow_FullMethodName        = "/opsguard.v1.ManagementService/CheckFlow"
	ManagementService_ListEvents_FullMethodName       = "/opsguard.v1.ManagementService/ListEvents"
	ManagementService_ListAudit_FullMethodName        = "/opsguard.v1.ManagementService/ListAudit"
	ManagementService_StreamLogs_FullMethodName       = "/opsguard.v1.ManagementService/StreamLogs"
	ManagementService_SubscribeEvents_FullMethodName  = "/opsguard.v1.ManagementService/SubscribeEvents"
	ManagementService_SubscribeAudit_FullMethodName   = "/opsguard.v1.ManagementService/SubscribeAudit"
	ManagementService_Tunnel_FullMethodName           = "/opsguard.v1.ManagementService/Tunnel"
)

// ManagementServiceClient is the client API for ManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ManagementService is the full server↔worker management API.
type ManagementServiceClient interface {
	// ---- liveness ----
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Pong, error)
	Self(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SelfInfo, error)
	// ---- workload read ----
	// ListServices returns Docker-native service objects (server maps to the
	// frontend-friendly Workload view).
	ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error)
	GetService(ctx context.Context, in *GetServiceRequest, opts ...grpc.CallOption) (*ServiceDetail, error)
	// ---- workload write (orchestration) ----
	// Writes are only executed on the swarm Raft leader; non-leader managers
	// forward to the leader over an internal gRPC client (same service).
	Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*Operation, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*Operation, error)
	Scale(ctx context.Context, in *ScaleRequest, opts ...grpc.CallOption) (*Operation, error)
	Restart(ctx context.Context, in *RestartRequest, opts ...grpc.CallOption) (*Operation, error)
	Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*Operation, error)
	GetOperation(ctx context.Context, in *GetOperationRequest, opts ...grpc.CallOption) (*Operation, error)
	// ---- node / host inspection ----
	ListNodes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListNodesResponse, error)
	NodeStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeStatsResponse, error)
	NodeProcesses(ctx context.Context, in *NodeProcessesRequest, opts ...grpc.CallOption) (*ProcessesResponse, error)
	NodeContainers(ctx context.Context, in *NodeContainersRequest, opts ...grpc.CallOption) (*NodeContainersResponse, error)
	// ---- container actions (standalone docker run containers) ----
	// Restart a container on a node; the node is resolved by ID or hostname
	// (same semantics as NodeContainers' node_id).
	RestartContainer(ctx context.Context, in *ContainerActionRequest, opts ...grpc.CallOption) (*ContainerActionResult, error)
	// ---- connectivity / HTTP probes ----
	CheckPort(ctx context.Context, in *CheckPortRequest, opts ...grpc.CallOption) (*PortCheckResult, error)
	CheckHTTP(ctx context.Context, in *CheckHTTPRequest, opts ...grpc.CallOption) (*HTTPCheckResult, error)
	CheckFlow(ctx context.Context, in *CheckFlowRequest, opts ...grpc.CallOption) (*FlowCheckResult, error)
	// ---- point-in-time event/audit query (frontend pass-through) ----
	ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error)
	ListAudit(ctx context.Context, in *ListAuditRequest, opts ...grpc.CallOption) (*ListAuditResponse, error)
	// ---- streaming ----
	// Server-streaming log lines (replaces the SSE /local/logs endpoint).
	StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogLine], error)
	// Bidirectional event subscription (replaces the webhook push). The server
	// opens the stream; the first message it sends carries the resume cursor
	// (after_seq). The Worker streams events back, and the server acks each
	// received seq so the Worker can garbage-collect persisted-but-acked
	// entries. On reconnect the server resumes from the last persisted cursor.
	SubscribeEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SubscribeRequest, MonitorEvent], error)
	SubscribeAudit(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SubscribeRequest, AuditEntry], error)
	// ---- idp reverse tunnel ----
	// Bidirectional HTTP-tunnel stream opened by the server (the one-way network
	// policy still holds). The Worker forwards IdP-bound HTTP requests from
	// in-cluster clients (e.g. r-nacos OIDC) as TunnelFrame request frames; the
	// server proxies them to its local IdP and returns TunnelFrame response frames
	// keyed by id. This lets services in an isolated cluster reach the management
	// plane's IdP endpoints without a reverse firewall hole.
	Tunnel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TunnelFrame, TunnelFrame], error)
}

type managementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewManagementServiceClient(cc grpc.ClientConnInterface) ManagementServiceClient {
	return &managementServiceClient{cc}
}

func (c *managementServiceClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Pong, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Pong)
	err := c.cc.Invoke(ctx, ManagementService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) Self(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SelfInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelfInfo)
	err := c.cc.Invoke(ctx, ManagementService_Self_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServicesResponse)
	err := c.cc.Invoke(ctx, ManagementService_ListServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) GetService(ctx context.Context, in *GetServiceRequest, opts ...grpc.CallOption) (*ServiceDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceDetail)
	err := c.cc.Invoke(ctx, ManagementService_GetService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, ManagementService_Deploy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, ManagementService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) Scale(ctx context.Context, in *ScaleRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, ManagementService_Scale_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) Restart(ctx context.Context, in *RestartRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, ManagementService_Restart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, ManagementService_Remove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) GetOperation(ctx context.Context, in *GetOperationRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, ManagementService_GetOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) ListNodes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, ManagementService_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) NodeStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeStatsResponse)
	err := c.cc.Invoke(ctx, ManagementService_NodeStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) NodeProcesses(ctx context.Context, in *NodeProcessesRequest, opts ...grpc.CallOption) (*ProcessesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessesResponse)
	err := c.cc.Invoke(ctx, ManagementService_NodeProcesses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) NodeContainers(ctx context.Context, in *NodeContainersRequest, opts ...grpc.CallOption) (*NodeContainersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeContainersResponse)
	err := c.cc.Invoke(ctx, ManagementService_NodeContainers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) RestartContainer(ctx context.Context, in *ContainerActionRequest, opts ...grpc.CallOption) (*ContainerActionResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContainerActionResult)
	err := c.cc.Invoke(ctx, ManagementService_RestartContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) CheckPort(ctx context.Context, in *CheckPortRequest, opts ...grpc.CallOption) (*PortCheckResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PortCheckResult)
	err := c.cc.Invoke(ctx, ManagementService_CheckPort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) CheckHTTP(ctx context.Context, in *CheckHTTPRequest, opts ...grpc.CallOption) (*HTTPCheckResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HTTPCheckResult)
	err := c.cc.Invoke(ctx, ManagementService_CheckHTTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) CheckFlow(ctx context.Context, in *CheckFlowRequest, opts ...grpc.CallOption) (*FlowCheckResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlowCheckResult)
	err := c.cc.Invoke(ctx, ManagementService_CheckFlow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEventsResponse)
	err := c.cc.Invoke(ctx, ManagementService_ListEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) ListAudit(ctx context.Context, in *ListAuditRequest, opts ...grpc.CallOption) (*ListAuditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAuditResponse)
	err := c.cc.Invoke(ctx, ManagementService_ListAudit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogLine], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ManagementService_ServiceDesc.Streams[0], ManagementService_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamLogsRequest, LogLine]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_StreamLogsClient = grpc.ServerStreamingClient[LogLine]

func (c *managementServiceClient) SubscribeEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SubscribeRequest, MonitorEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ManagementService_ServiceDesc.Streams[1], ManagementService_SubscribeEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, MonitorEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_SubscribeEventsClient = grpc.BidiStreamingClient[SubscribeRequest, MonitorEvent]

func (c *managementServiceClient) SubscribeAudit(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SubscribeRequest, AuditEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ManagementService_ServiceDesc.Streams[2], ManagementService_SubscribeAudit_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, AuditEntry]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_SubscribeAuditClient = grpc.BidiStreamingClient[SubscribeRequest, AuditEntry]

func (c *managementServiceClient) Tunnel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TunnelFrame, TunnelFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ManagementService_ServiceDesc.Streams[3], ManagementService_Tunnel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TunnelFrame, TunnelFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_TunnelClient = grpc.BidiStreamingClient[TunnelFrame, TunnelFrame]

// ManagementServiceServer is the server API for ManagementService service.
// All implementations must embed UnimplementedManagementServiceServer
// for forward compatibility.
//
// ManagementService is the full server↔worker management API.
type ManagementServiceServer interface {
	// ---- liveness ----
	Ping(context.Context, *Empty) (*Pong, error)
	Self(context.Context, *Empty) (*SelfInfo, error)
	// ---- workload read ----
	// ListServices returns Docker-native service objects (server maps to the
	// frontend-friendly Workload view).
	ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error)
	GetService(context.Context, *GetServiceRequest) (*ServiceDetail, error)
	// ---- workload write (orchestration) ----
	// Writes are only executed on the swarm Raft leader; non-leader managers
	// forward to the leader over an internal gRPC client (same service).
	Deploy(context.Context, *DeployRequest) (*Operation, error)
	Update(context.Context, *UpdateRequest) (*Operation, error)
	Scale(context.Context, *ScaleRequest) (*Operation, error)
	Restart(context.Context, *RestartRequest) (*Operation, error)
	Remove(context.Context, *RemoveRequest) (*Operation, error)
	GetOperation(context.Context, *GetOperationRequest) (*Operation, error)
	// ---- node / host inspection ----
	ListNodes(context.Context, *Empty) (*ListNodesResponse, error)
	NodeStats(context.Context, *Empty) (*NodeStatsResponse, error)
	NodeProcesses(context.Context, *NodeProcessesRequest) (*ProcessesResponse, error)
	NodeContainers(context.Context, *NodeContainersRequest) (*NodeContainersResponse, error)
	// ---- container actions (standalone docker run containers) ----
	// Restart a container on a node; the node is resolved by ID or hostname
	// (same semantics as NodeContainers' node_id).
	RestartContainer(context.Context, *ContainerActionRequest) (*ContainerActionResult, error)
	// ---- connectivity / HTTP probes ----
	CheckPort(context.Context, *CheckPortRequest) (*PortCheckResult, error)
	CheckHTTP(context.Context, *CheckHTTPRequest) (*HTTPCheckResult, error)
	CheckFlow(context.Context, *CheckFlowRequest) (*FlowCheckResult, error)
	// ---- point-in-time event/audit query (frontend pass-through) ----
	ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error)
	ListAudit(context.Context, *ListAuditRequest) (*ListAuditResponse, error)
	// ---- streaming ----
	// Server-streaming log lines (replaces the SSE /local/logs endpoint).
	StreamLogs(*StreamLogsRequest, grpc.ServerStreamingServer[LogLine]) error
	// Bidirectional event subscription (replaces the webhook push). The server
	// opens the stream; the first message it sends carries the resume cursor
	// (after_seq). The Worker streams events back, and the server acks each
	// received seq so the Worker can garbage-collect persisted-but-acked
	// entries. On reconnect the server resumes from the last persisted cursor.
	SubscribeEvents(grpc.BidiStreamingServer[SubscribeRequest, MonitorEvent]) error
	SubscribeAudit(grpc.BidiStreamingServer[SubscribeRequest, AuditEntry]) error
	// ---- idp reverse tunnel ----
	// Bidirectional HTTP-tunnel stream opened by the server (the one-way network
	// policy still holds). The Worker forwards IdP-bound HTTP requests from
	// in-cluster clients (e.g. r-nacos OIDC) as TunnelFrame request frames; the
	// server proxies them to its local IdP and returns TunnelFrame response frames
	// keyed by id. This lets services in an isolated cluster reach the management
	// plane's IdP endpoints without a reverse firewall hole.
	Tunnel(grpc.BidiStreamingServer[TunnelFrame, TunnelFrame]) error
	mustEmbedUnimplementedManagementServiceServer()
}

// UnimplementedManagementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedManagementServiceServer struct{}

func (UnimplementedManagementServiceServer) Ping(context.Context, *Empty) (*Pong, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedManagementServiceServer) Self(context.Context, *Empty) (*SelfInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Self not implemented")
}
func (UnimplementedManagementServiceServer) ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedManagementServiceServer) GetService(context.Context, *GetServiceRequest) (*ServiceDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetService not implemented")
}
func (UnimplementedManagementServiceServer) Deploy(context.Context, *DeployRequest) (*Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method Deploy not implemented")
}
func (UnimplementedManagementServiceServer) Update(context.Context, *UpdateRequest) (*Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedManagementServiceServer) Scale(context.Context, *ScaleRequest) (*Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method Scale not implemented")
}
func (UnimplementedManagementServiceServer) Restart(context.Context, *RestartRequest) (*Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method Restart not implemented")
}
func (UnimplementedManagementServiceServer) Remove(context.Context, *RemoveRequest) (*Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedManagementServiceServer) GetOperation(context.Context, *GetOperationRequest) (*Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOperation not implemented")
}
func (UnimplementedManagementServiceServer) ListNodes(context.Context, *Empty) (*ListNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedManagementServiceServer) NodeStats(context.Context, *Empty) (*NodeStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NodeStats not implemented")
}
func (UnimplementedManagementServiceServer) NodeProcesses(context.Context, *NodeProcessesRequest) (*ProcessesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NodeProcesses not implemented")
}
func (UnimplementedManagementServiceServer) NodeContainers(context.Context, *NodeContainersRequest) (*NodeContainersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NodeContainers not implemented")
}
func (UnimplementedManagementServiceServer) RestartContainer(context.Context, *ContainerActionRequest) (*ContainerActionResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartContainer not implemented")
}
func (UnimplementedManagementServiceServer) CheckPort(context.Context, *CheckPortRequest) (*PortCheckResult, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckPort not implemented")
}
func (UnimplementedManagementServiceServer) CheckHTTP(context.Context, *CheckHTTPRequest) (*HTTPCheckResult, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckHTTP not implemented")
}
func (UnimplementedManagementServiceServer) CheckFlow(context.Context, *CheckFlowRequest) (*FlowCheckResult, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckFlow not implemented")
}
func (UnimplementedManagementServiceServer) ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEvents not implemented")
}
func (UnimplementedManagementServiceServer) ListAudit(context.Context, *ListAuditRequest) (*ListAuditResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAudit not implemented")
}
func (UnimplementedManagementServiceServer) StreamLogs(*StreamLogsRequest, grpc.ServerStreamingServer[LogLine]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedManagementServiceServer) SubscribeEvents(grpc.BidiStreamingServer[SubscribeRequest, MonitorEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeEvents not implemented")
}
func (UnimplementedManagementServiceServer) SubscribeAudit(grpc.BidiStreamingServer[SubscribeRequest, AuditEntry]) error {
	return status.Error(codes.Unimplemented, "method SubscribeAudit not implemented")
}
func (UnimplementedManagementServiceServer) Tunnel(grpc.BidiStreamingServer[TunnelFrame, TunnelFrame]) error {
	return status.Error(codes.Unimplemented, "method Tunnel not implemented")
}
func (UnimplementedManagementServiceServer) mustEmbedUnimplementedManagementServiceServer() {}
func (UnimplementedManagementServiceServer) testEmbeddedByValue()                           {}

// UnsafeManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManagementServiceServer will
// result in compilation errors.
type UnsafeManagementServiceServer interface {
	mustEmbedUnimplementedManagementServiceServer()
}

func RegisterManagementServiceServer(s grpc.ServiceRegistrar, srv ManagementServiceServer) {
	// If the following call panics, it indicates UnimplementedManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ManagementService_ServiceDesc, srv)
}

func _ManagementService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_Self_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).Self(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_Self_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).Self(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).ListServices(ctx, req.(*ListServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_GetService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GetService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_GetService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GetService(ctx, req.(*GetServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_Deploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).Deploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_Deploy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).Deploy(ctx, req.(*DeployRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_Scale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScaleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).Scale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_Scale_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).Scale(ctx, req.(*ScaleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_Restart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).Restart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_Restart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).Restart(ctx, req.(*RestartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).Remove(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_GetOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GetOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_GetOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GetOperation(ctx, req.(*GetOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).ListNodes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_NodeStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).NodeStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_NodeStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).NodeStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_NodeProcesses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeProcessesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).NodeProcesses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_NodeProcesses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).NodeProcesses(ctx, req.(*NodeProcessesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_NodeContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeContainersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).NodeContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_NodeContainers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).NodeContainers(ctx, req.(*NodeContainersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_RestartContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).RestartContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_RestartContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).RestartContainer(ctx, req.(*ContainerActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_CheckPort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).CheckPort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_CheckPort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).CheckPort(ctx, req.(*CheckPortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_CheckHTTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckHTTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).CheckHTTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_CheckHTTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).CheckHTTP(ctx, req.(*CheckHTTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_CheckFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).CheckFlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_CheckFlow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).CheckFlow(ctx, req.(*CheckFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_ListEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).ListEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_ListEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).ListEvents(ctx, req.(*ListEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_ListAudit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).ListAudit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_ListAudit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).ListAudit(ctx, req.(*ListAuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ManagementServiceServer).StreamLogs(m, &grpc.GenericServerStream[StreamLogsRequest, LogLine]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_StreamLogsServer = grpc.ServerStreamingServer[LogLine]

func _ManagementService_SubscribeEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ManagementServiceServer).SubscribeEvents(&grpc.GenericServerStream[SubscribeRequest, MonitorEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_SubscribeEventsServer = grpc.BidiStreamingServer[SubscribeRequest, MonitorEvent]

func _ManagementService_SubscribeAudit_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ManagementServiceServer).SubscribeAudit(&grpc.GenericServerStream[SubscribeRequest, AuditEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_SubscribeAuditServer = grpc.BidiStreamingServer[SubscribeRequest, AuditEntry]

func _ManagementService_Tunnel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ManagementServiceServer).Tunnel(&grpc.GenericServerStream[TunnelFrame, TunnelFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_TunnelServer = grpc.BidiStreamingServer[TunnelFrame, TunnelFrame]

// ManagementService_ServiceDesc is the grpc.ServiceDesc for ManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "opsguard.v1.ManagementService",
	HandlerType: (*ManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ManagementService_Ping_Handler,
		},
		{
			MethodName: "Self",
			Handler:    _ManagementService_Self_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _ManagementService_ListServices_Handler,
		},
		{
			MethodName: "GetService",
			Handler:    _ManagementService_GetService_Handler,
		},
		{
			MethodName: "Deploy",
			Handler:    _ManagementService_Deploy_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ManagementService_Update_Handler,
		},
		{
			MethodName: "Scale",
			Handler:    _ManagementService_Scale_Handler,
		},
		{
			MethodName: "Restart",
			Handler:    _ManagementService_Restart_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _ManagementService_Remove_Handler,
		},
		{
			MethodName: "GetOperation",
			Handler:    _ManagementService_GetOperation_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _ManagementService_ListNodes_Handler,
		},
		{
			MethodName: "NodeStats",
			Handler:    _ManagementService_NodeStats_Handler,
		},
		{
			MethodName: "NodeProcesses",
			Handler:    _ManagementService_NodeProcesses_Handler,
		},
		{
			MethodName: "NodeContainers",
			Handler:    _ManagementService_NodeContainers_Handler,
		},
		{
			MethodName: "RestartContainer",
			Handler:    _ManagementService_RestartContainer_Handler,
		},
		{
			MethodName: "CheckPort",
			Handler:    _ManagementService_CheckPort_Handler,
		},
		{
			MethodName: "CheckHTTP",
			Handler:    _ManagementService_CheckHTTP_Handler,
		},
		{
			MethodName: "CheckFlow",
			Handler:    _ManagementService_CheckFlow_Handler,
		},
		{
			MethodName: "ListEvents",
			Handler:    _ManagementService_ListEvents_Handler,
		},
		{
			MethodName: "ListAudit",
			Handler:    _ManagementService_ListAudit_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _ManagementService_StreamLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeEvents",
			Handler:       _ManagementService_SubscribeEvents_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SubscribeAudit",
			Handler:       _ManagementService_SubscribeAudit_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Tunnel",
			Handler:       _ManagementService_Tunnel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "opsguard.proto",
}
